name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Empfohlene LTS-Version
        cache: 'npm'

    - name: Install dependencies
      run: npm ci # Clean install für bessere Konsistenz

    - name: Build project
      run: npm run build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # Kein PAT nötig
        publish_dir: ./dist # Korrekter relativer Pfad
        keep_files: false # Alte Dateien löschen